/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedObjetivosRouteImport } from './routes/_authenticated/objetivos'
import { Route as AuthenticatedTrocarSenhaRouteImport } from './routes/_authenticated/trocar-senha'
import { Route as AuthenticatedBibliotecaArquivosRouteImport } from './routes/_authenticated/biblioteca/arquivos'
import { Route as AuthenticatedBibliotecaCoresRouteImport } from './routes/_authenticated/biblioteca/cores'
import { Route as AuthenticatedBibliotecaMarcaRouteImport } from './routes/_authenticated/biblioteca/marca'
import { Route as AuthenticatedBibliotecaMedidasRouteImport } from './routes/_authenticated/biblioteca/medidas'
import { Route as AuthenticatedBibliotecaProdutosRouteImport } from './routes/_authenticated/biblioteca/produtos'
import { Route as AuthenticatedBibliotecaTextosRouteImport } from './routes/_authenticated/biblioteca/textos'
import { Route as AuthenticatedEstrategiaAtaRouteImport } from './routes/_authenticated/estrategia/ata'
import { Route as AuthenticatedSocialStoriesRouteImport } from './routes/_authenticated/social/stories'
import { Route as AuthenticatedTarefasCalendarioRouteImport } from './routes/_authenticated/tarefas/calendario'
import { Route as AuthenticatedTarefasMeuDiaRouteImport } from './routes/_authenticated/tarefas/meu-dia'
import { Route as AuthenticatedTarefasMeuTrabalhoRouteImport } from './routes/_authenticated/tarefas/meu-trabalho'
import { Route as AuthenticatedTarefasQuadrosRouteImport } from './routes/_authenticated/tarefas/quadros'
import { Route as AuthenticatedTarefasQuadrosQuadroIdRouteImport } from './routes/_authenticated/tarefas/quadros_.$quadroId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObjetivosRoute = AuthenticatedObjetivosRouteImport.update({
  id: '/objetivos',
  path: '/objetivos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrocarSenhaRoute =
  AuthenticatedTrocarSenhaRouteImport.update({
    id: '/trocar-senha',
    path: '/trocar-senha',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaArquivosRoute =
  AuthenticatedBibliotecaArquivosRouteImport.update({
    id: '/biblioteca/arquivos',
    path: '/biblioteca/arquivos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaCoresRoute =
  AuthenticatedBibliotecaCoresRouteImport.update({
    id: '/biblioteca/cores',
    path: '/biblioteca/cores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaMarcaRoute =
  AuthenticatedBibliotecaMarcaRouteImport.update({
    id: '/biblioteca/marca',
    path: '/biblioteca/marca',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaMedidasRoute =
  AuthenticatedBibliotecaMedidasRouteImport.update({
    id: '/biblioteca/medidas',
    path: '/biblioteca/medidas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaProdutosRoute =
  AuthenticatedBibliotecaProdutosRouteImport.update({
    id: '/biblioteca/produtos',
    path: '/biblioteca/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaTextosRoute =
  AuthenticatedBibliotecaTextosRouteImport.update({
    id: '/biblioteca/textos',
    path: '/biblioteca/textos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstrategiaAtaRoute =
  AuthenticatedEstrategiaAtaRouteImport.update({
    id: '/estrategia/ata',
    path: '/estrategia/ata',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSocialStoriesRoute =
  AuthenticatedSocialStoriesRouteImport.update({
    id: '/social/stories',
    path: '/social/stories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasCalendarioRoute =
  AuthenticatedTarefasCalendarioRouteImport.update({
    id: '/tarefas/calendario',
    path: '/tarefas/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasMeuDiaRoute =
  AuthenticatedTarefasMeuDiaRouteImport.update({
    id: '/tarefas/meu-dia',
    path: '/tarefas/meu-dia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasMeuTrabalhoRoute =
  AuthenticatedTarefasMeuTrabalhoRouteImport.update({
    id: '/tarefas/meu-trabalho',
    path: '/tarefas/meu-trabalho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasQuadrosRoute =
  AuthenticatedTarefasQuadrosRouteImport.update({
    id: '/tarefas/quadros',
    path: '/tarefas/quadros',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasQuadrosQuadroIdRoute =
  AuthenticatedTarefasQuadrosQuadroIdRouteImport.update({
    id: '/tarefas/quadros_/$quadroId',
    path: '/tarefas/quadros/$quadroId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/objetivos': typeof AuthenticatedObjetivosRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/biblioteca/arquivos': typeof AuthenticatedBibliotecaArquivosRoute
  '/biblioteca/cores': typeof AuthenticatedBibliotecaCoresRoute
  '/biblioteca/marca': typeof AuthenticatedBibliotecaMarcaRoute
  '/biblioteca/medidas': typeof AuthenticatedBibliotecaMedidasRoute
  '/biblioteca/produtos': typeof AuthenticatedBibliotecaProdutosRoute
  '/biblioteca/textos': typeof AuthenticatedBibliotecaTextosRoute
  '/estrategia/ata': typeof AuthenticatedEstrategiaAtaRoute
  '/social/stories': typeof AuthenticatedSocialStoriesRoute
  '/tarefas/calendario': typeof AuthenticatedTarefasCalendarioRoute
  '/tarefas/meu-dia': typeof AuthenticatedTarefasMeuDiaRoute
  '/tarefas/meu-trabalho': typeof AuthenticatedTarefasMeuTrabalhoRoute
  '/tarefas/quadros': typeof AuthenticatedTarefasQuadrosRoute
  '/tarefas/quadros/$quadroId': typeof AuthenticatedTarefasQuadrosQuadroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/objetivos': typeof AuthenticatedObjetivosRoute
  '/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/biblioteca/arquivos': typeof AuthenticatedBibliotecaArquivosRoute
  '/biblioteca/cores': typeof AuthenticatedBibliotecaCoresRoute
  '/biblioteca/marca': typeof AuthenticatedBibliotecaMarcaRoute
  '/biblioteca/medidas': typeof AuthenticatedBibliotecaMedidasRoute
  '/biblioteca/produtos': typeof AuthenticatedBibliotecaProdutosRoute
  '/biblioteca/textos': typeof AuthenticatedBibliotecaTextosRoute
  '/estrategia/ata': typeof AuthenticatedEstrategiaAtaRoute
  '/social/stories': typeof AuthenticatedSocialStoriesRoute
  '/tarefas/calendario': typeof AuthenticatedTarefasCalendarioRoute
  '/tarefas/meu-dia': typeof AuthenticatedTarefasMeuDiaRoute
  '/tarefas/meu-trabalho': typeof AuthenticatedTarefasMeuTrabalhoRoute
  '/tarefas/quadros': typeof AuthenticatedTarefasQuadrosRoute
  '/tarefas/quadros/$quadroId': typeof AuthenticatedTarefasQuadrosQuadroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/objetivos': typeof AuthenticatedObjetivosRoute
  '/_authenticated/trocar-senha': typeof AuthenticatedTrocarSenhaRoute
  '/_authenticated/biblioteca/arquivos': typeof AuthenticatedBibliotecaArquivosRoute
  '/_authenticated/biblioteca/cores': typeof AuthenticatedBibliotecaCoresRoute
  '/_authenticated/biblioteca/marca': typeof AuthenticatedBibliotecaMarcaRoute
  '/_authenticated/biblioteca/medidas': typeof AuthenticatedBibliotecaMedidasRoute
  '/_authenticated/biblioteca/produtos': typeof AuthenticatedBibliotecaProdutosRoute
  '/_authenticated/biblioteca/textos': typeof AuthenticatedBibliotecaTextosRoute
  '/_authenticated/estrategia/ata': typeof AuthenticatedEstrategiaAtaRoute
  '/_authenticated/social/stories': typeof AuthenticatedSocialStoriesRoute
  '/_authenticated/tarefas/calendario': typeof AuthenticatedTarefasCalendarioRoute
  '/_authenticated/tarefas/meu-dia': typeof AuthenticatedTarefasMeuDiaRoute
  '/_authenticated/tarefas/meu-trabalho': typeof AuthenticatedTarefasMeuTrabalhoRoute
  '/_authenticated/tarefas/quadros': typeof AuthenticatedTarefasQuadrosRoute
  '/_authenticated/tarefas/quadros_/$quadroId': typeof AuthenticatedTarefasQuadrosQuadroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/objetivos'
    | '/trocar-senha'
    | '/biblioteca/arquivos'
    | '/biblioteca/cores'
    | '/biblioteca/marca'
    | '/biblioteca/medidas'
    | '/biblioteca/produtos'
    | '/biblioteca/textos'
    | '/estrategia/ata'
    | '/social/stories'
    | '/tarefas/calendario'
    | '/tarefas/meu-dia'
    | '/tarefas/meu-trabalho'
    | '/tarefas/quadros'
    | '/tarefas/quadros/$quadroId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/objetivos'
    | '/trocar-senha'
    | '/biblioteca/arquivos'
    | '/biblioteca/cores'
    | '/biblioteca/marca'
    | '/biblioteca/medidas'
    | '/biblioteca/produtos'
    | '/biblioteca/textos'
    | '/estrategia/ata'
    | '/social/stories'
    | '/tarefas/calendario'
    | '/tarefas/meu-dia'
    | '/tarefas/meu-trabalho'
    | '/tarefas/quadros'
    | '/tarefas/quadros/$quadroId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/objetivos'
    | '/_authenticated/trocar-senha'
    | '/_authenticated/biblioteca/arquivos'
    | '/_authenticated/biblioteca/cores'
    | '/_authenticated/biblioteca/marca'
    | '/_authenticated/biblioteca/medidas'
    | '/_authenticated/biblioteca/produtos'
    | '/_authenticated/biblioteca/textos'
    | '/_authenticated/estrategia/ata'
    | '/_authenticated/social/stories'
    | '/_authenticated/tarefas/calendario'
    | '/_authenticated/tarefas/meu-dia'
    | '/_authenticated/tarefas/meu-trabalho'
    | '/_authenticated/tarefas/quadros'
    | '/_authenticated/tarefas/quadros_/$quadroId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/objetivos': {
      id: '/_authenticated/objetivos'
      path: '/objetivos'
      fullPath: '/objetivos'
      preLoaderRoute: typeof AuthenticatedObjetivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trocar-senha': {
      id: '/_authenticated/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof AuthenticatedTrocarSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/arquivos': {
      id: '/_authenticated/biblioteca/arquivos'
      path: '/biblioteca/arquivos'
      fullPath: '/biblioteca/arquivos'
      preLoaderRoute: typeof AuthenticatedBibliotecaArquivosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/cores': {
      id: '/_authenticated/biblioteca/cores'
      path: '/biblioteca/cores'
      fullPath: '/biblioteca/cores'
      preLoaderRoute: typeof AuthenticatedBibliotecaCoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/marca': {
      id: '/_authenticated/biblioteca/marca'
      path: '/biblioteca/marca'
      fullPath: '/biblioteca/marca'
      preLoaderRoute: typeof AuthenticatedBibliotecaMarcaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/medidas': {
      id: '/_authenticated/biblioteca/medidas'
      path: '/biblioteca/medidas'
      fullPath: '/biblioteca/medidas'
      preLoaderRoute: typeof AuthenticatedBibliotecaMedidasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/produtos': {
      id: '/_authenticated/biblioteca/produtos'
      path: '/biblioteca/produtos'
      fullPath: '/biblioteca/produtos'
      preLoaderRoute: typeof AuthenticatedBibliotecaProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca/textos': {
      id: '/_authenticated/biblioteca/textos'
      path: '/biblioteca/textos'
      fullPath: '/biblioteca/textos'
      preLoaderRoute: typeof AuthenticatedBibliotecaTextosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategia/ata': {
      id: '/_authenticated/estrategia/ata'
      path: '/estrategia/ata'
      fullPath: '/estrategia/ata'
      preLoaderRoute: typeof AuthenticatedEstrategiaAtaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/social/stories': {
      id: '/_authenticated/social/stories'
      path: '/social/stories'
      fullPath: '/social/stories'
      preLoaderRoute: typeof AuthenticatedSocialStoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/calendario': {
      id: '/_authenticated/tarefas/calendario'
      path: '/tarefas/calendario'
      fullPath: '/tarefas/calendario'
      preLoaderRoute: typeof AuthenticatedTarefasCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/meu-dia': {
      id: '/_authenticated/tarefas/meu-dia'
      path: '/tarefas/meu-dia'
      fullPath: '/tarefas/meu-dia'
      preLoaderRoute: typeof AuthenticatedTarefasMeuDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/meu-trabalho': {
      id: '/_authenticated/tarefas/meu-trabalho'
      path: '/tarefas/meu-trabalho'
      fullPath: '/tarefas/meu-trabalho'
      preLoaderRoute: typeof AuthenticatedTarefasMeuTrabalhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/quadros': {
      id: '/_authenticated/tarefas/quadros'
      path: '/tarefas/quadros'
      fullPath: '/tarefas/quadros'
      preLoaderRoute: typeof AuthenticatedTarefasQuadrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/quadros_/$quadroId': {
      id: '/_authenticated/tarefas/quadros_/$quadroId'
      path: '/tarefas/quadros/$quadroId'
      fullPath: '/tarefas/quadros/$quadroId'
      preLoaderRoute: typeof AuthenticatedTarefasQuadrosQuadroIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedObjetivosRoute: typeof AuthenticatedObjetivosRoute
  AuthenticatedTrocarSenhaRoute: typeof AuthenticatedTrocarSenhaRoute
  AuthenticatedBibliotecaArquivosRoute: typeof AuthenticatedBibliotecaArquivosRoute
  AuthenticatedBibliotecaCoresRoute: typeof AuthenticatedBibliotecaCoresRoute
  AuthenticatedBibliotecaMarcaRoute: typeof AuthenticatedBibliotecaMarcaRoute
  AuthenticatedBibliotecaMedidasRoute: typeof AuthenticatedBibliotecaMedidasRoute
  AuthenticatedBibliotecaProdutosRoute: typeof AuthenticatedBibliotecaProdutosRoute
  AuthenticatedBibliotecaTextosRoute: typeof AuthenticatedBibliotecaTextosRoute
  AuthenticatedEstrategiaAtaRoute: typeof AuthenticatedEstrategiaAtaRoute
  AuthenticatedSocialStoriesRoute: typeof AuthenticatedSocialStoriesRoute
  AuthenticatedTarefasCalendarioRoute: typeof AuthenticatedTarefasCalendarioRoute
  AuthenticatedTarefasMeuDiaRoute: typeof AuthenticatedTarefasMeuDiaRoute
  AuthenticatedTarefasMeuTrabalhoRoute: typeof AuthenticatedTarefasMeuTrabalhoRoute
  AuthenticatedTarefasQuadrosRoute: typeof AuthenticatedTarefasQuadrosRoute
  AuthenticatedTarefasQuadrosQuadroIdRoute: typeof AuthenticatedTarefasQuadrosQuadroIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedObjetivosRoute: AuthenticatedObjetivosRoute,
  AuthenticatedTrocarSenhaRoute: AuthenticatedTrocarSenhaRoute,
  AuthenticatedBibliotecaArquivosRoute: AuthenticatedBibliotecaArquivosRoute,
  AuthenticatedBibliotecaCoresRoute: AuthenticatedBibliotecaCoresRoute,
  AuthenticatedBibliotecaMarcaRoute: AuthenticatedBibliotecaMarcaRoute,
  AuthenticatedBibliotecaMedidasRoute: AuthenticatedBibliotecaMedidasRoute,
  AuthenticatedBibliotecaProdutosRoute: AuthenticatedBibliotecaProdutosRoute,
  AuthenticatedBibliotecaTextosRoute: AuthenticatedBibliotecaTextosRoute,
  AuthenticatedEstrategiaAtaRoute: AuthenticatedEstrategiaAtaRoute,
  AuthenticatedSocialStoriesRoute: AuthenticatedSocialStoriesRoute,
  AuthenticatedTarefasCalendarioRoute: AuthenticatedTarefasCalendarioRoute,
  AuthenticatedTarefasMeuDiaRoute: AuthenticatedTarefasMeuDiaRoute,
  AuthenticatedTarefasMeuTrabalhoRoute: AuthenticatedTarefasMeuTrabalhoRoute,
  AuthenticatedTarefasQuadrosRoute: AuthenticatedTarefasQuadrosRoute,
  AuthenticatedTarefasQuadrosQuadroIdRoute:
    AuthenticatedTarefasQuadrosQuadroIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
